language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "tulioviglione-github"
    token:
      secure: "06033e68e7067955ed954000f46d5967147e89c9"
jdk:
  - openjdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
before_install:
  - chmod +x mvnw
